name: CI Pipeline
on:
  pull_request:
    types: [ opened ]
    branches:
      - main
jobs:
  ci-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: calebtraceyco/devops/jobs/go-package.yml
