name: CI Pipeline
on:
  push:
    branches: [ FEAT-*, $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  ci-workflow:
    uses: ./devops/.github/workflows/go-package.yml@main
