name: CI Pipeline
on:
  push:
    branches:
      - FEAT-*
      - main
  pull_request:
    branches:
      - main
jobs:
  ci-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: ./.github/devops/jobs/go-package.yml
